import com.eurodyn.qlack.test.cmd.model.Account
import com.eurodyn.qlack.test.cmd.model.AccountStatus

global com.eurodyn.qlack.test.cmd.component.AccountComponent accountComponent;

rule "accountBalanceAtLeast100"
  when
    $account : Account(balance < 100)
  then
    System.out.println("The balance of the account " +$account.getId()+ " is significantly low.");
end

rule "accountIsActive"
  when
    $account : Account((status == AccountStatus.INACTIVE) && (balance > 0))
  then
    $account.setStatus(AccountStatus.ACTIVE);
    accountComponent.save($account);
    System.out.println("The account " +$account.getId()+ " has been activated.");
end

rule "accountIsInactive"
  when
    $account : Account((status == AccountStatus.ACTIVE) && (balance == 0))
  then
    $account.setStatus(AccountStatus.INACTIVE);
    accountComponent.save($account);
    System.out.println("The account " +$account.getId()+ " has been deactivated.");
end